import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { types } from "util";
import type { ReactNode } from 'react';

//この型を書くとなぜかbuildできた
type LayoutProps = {
  children: ReactNode;
  types: ReactNode;
  params?: any;
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: LayoutProps)
{
  return (
    <html lang="ja">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
